require: rubocop-rspec

Rails:
  Enabled: true
  
AllCops:
  UseCache: false
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'spec/internal/**/*'
    - 'misc/**/*'

Lint/UselessAssignment:
  Exclude:
    - 'spec/factories/*.rb'

Lint/UnderscorePrefixedVariableName:
  Exclude:
    - 'app/schemas/geo_concerns/basic_geo_metadata_required.rb'
    - 'app/models/concerns/geo_concerns/basic_geo_metadata.rb'

Metrics/LineLength:
  Max: 250
  Exclude:
    - 'app/models/concerns/geo_concerns/extractors/iso19139_helper.rb'
    - 'app/helpers/metadata_extraction_helper.rb'
    - 'app/models/concerns/file_set/image_file_behavior.rb'
    - 'app/models/concerns/file_set/raster_file_behavior.rb'
    - 'app/models/concerns/file_set/vector_file_behavior.rb'
    - 'app/models/concerns/georeferenced_behavior.rb'
    - 'app/models/solr_document.rb'
    - 'app/schemas/basic_geo_metadata_required.rb'
    - 'app/schemas/geo_concerns/basic_geo_metadata_required.rb'
    - 'config/**/*.rb'
    - 'app/values/geo_concerns/coverage.rb'
    - 'app/values/geo_concerns/time_period.rb'
    - 'lib/geo_concerns/fgdc_metadata_extractor.rb'
    - 'lib/generators/geo_concerns/install_generator.rb'
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/models/concerns/geo_concerns/extractors/iso19139_helper.rb'
    - 'lib/geo_concerns/fgdc_metadata_extractor.rb'
    - 'lib/geo_concerns/coverage.rb'
    - 'app/models/concerns/geo_concerns/basic_geo_metadata.rb'

Metrics/MethodLength:
  Exclude:
    - 'Rakefile'
    - 'app/models/concerns/geo_concerns/extractors/iso19139_helper.rb'
    - 'app/models/concerns/geo_concerns/basic_geo_metadata.rb'
    - 'lib/geo_concerns/coverage.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'lib/generators/geo_concerns/install_generator.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/geo_concerns/coverage.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ClosingParenthesisIndentation:
  Exclude:
    - 'spec/models/image_file_spec.rb'
    - 'spec/models/raster_file_spec.rb'
    - 'spec/models/vector_file_spec.rb'
    - 'spec/models/image_work_spec.rb'
    - 'spec/models/raster_work_spec.rb'
    - 'spec/models/vector_work_spec.rb'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'spec/models/image_file_spec.rb'
    - 'spec/models/raster_file_spec.rb'
    - 'spec/models/vector_file_spec.rb'
    - 'spec/models/image_work_spec.rb'
    - 'spec/models/raster_work_spec.rb'
    - 'spec/models/vector_work_spec.rb'

Style/SymbolProc:
  Exclude:
    - 'app/values/geo_concerns/coverage.rb'

Style/RedundantBegin:
  Exclude:
    - 'app/values/geo_concerns/coverage.rb'

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
