language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.1
script: bundle exec rake ci
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
  - jdk_switcher use oraclejdk8
  - gdalinfo --version
addons:
  apt:
    packages:
    - gdal-bin
